version: "3"
services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy/proxy
      dockerfile: Dockerfile
    ports:
      - "9002:9002" 
    networks:
      - temporal-network

  demo:
    container_name: demo
    build:
      context: ./Demo/Temporal_SpringBoot-master
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - temporal-network

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
