version: "3"
services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy/proxy
      dockerfile: Dockerfile
    ports:
      - "8001:8001" 

  Demo:
    container_name: Demo
    build:
      context: ./Demo/Temporal_Springoot-master
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    links:
      - proxy
