version: "3"
services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy/proxy
      dockerfile: Dockerfile
    ports:
      - "9002:9002" 

  demo:
    container_name: demo
    build:
      context: ./Demo/Temporal_SpringBoot-master
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    links:
      - proxy
