version: "3"
services:
  proxy:
    container_name: proxy
    build:
      image: skarmanya/temporal_proxy:v2
    ports:
      - "9002:9002" 
    networks:
        - swiggy-temporal-network

  demo:
    container_name: demo
    depends_on:
      - proxy
    build:
      image: skarmanya/temporal_demo:v16
    ports:
      - "8001:8001"
    networks:
      - swiggy-temporal-network
networks:
  swiggy-temporal-network:
    external:
      name: temporal-network
